name: Log latest release
on:
  push:
    branches:
      - main

jobs:
  getDiscussions:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_discussions
        with:
          query: |
            query getDiscussions($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                discussions(first:0) {
                  comments {
                    totalCount
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'Discussions: ${{ steps.get_discussions.outputs.data }}'"
